import type { Metadata } from "next";
import { Josefin_Sans, Lato } from 'next/font/google';
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const josefin = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-josefin',
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-lato',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${josefin.variable} ${lato.variable}`}>
        {children}
        
        </body>
    </html>
  );
}